import Mock from 'mockjs';
export default Mock.mock('module_icon', {
	'module_icon':[
		{
			value:'function1',
			src:'../../static/images/module/function1@3x.png'
		},
		{
			value:'function2',
			src:'../../static/images/module/function2@3x.png'
		},
		{
			value:'function3',
			src:'../../static/images/module/function3@3x.png'
		},
		{
			value:'function4',
			src:'../../static/images/module/function4@3x.png'
		},
		{
			value:'function5',
			src:'../../static/images/module/function5@3x.png'
		},
		{
			value:'function6',
			src:'../../static/images/module/function6@3x.png'
		},
		{
			value:'function7',
			src:'../../static/images/module/function7@3x.png'
		},
		{
			value:'function8',
			src:'../../static/images/module/function8@3x.png'
		},
		{
			value:'function9',
			src:'../../static/images/module/function9@3x.png'
		},
		{
			value:'function10',
			src:'../../static/images/module/function10@3x.png'
		},
		{
			value:'function11',
			src:'../../static/images/module/function11@3x.png'
		},
		{
			value:'function12',
			src:'../../static/images/module/function12@3x.png'
		},
		{
			value:'function13',
			src:'../../static/images/module/function13@3x.png'
		},
		{
			value:'function14',
			src:'../../static/images/module/function14@3x.png'
		},
		{
			value:'function15',
			src:'../../static/images/module/function15@3x.png'
		},
		{
			value:'function16',
			src:'../../static/images/module/function16@3x.png'
		},
		{
			value:'function17',
			src:'../../static/images/module/function17@3x.png'
		},
		{
			value:'function18',
			src:'../../static/images/module/function18@3x.png'
		},
		{
			value:'function19',
			src:'../../static/images/module/function19@3x.png'
		},
		{
			value:'function20',
			src:'../../static/images/module/function20@3x.png'
		},
		{
			value:'function21',
			src:'../../static/images/module/function21@3x.png'
		},
		{
			value:'function22',
			src:'../../static/images/module/function22@3x.png'
		},
		{
			value:'function23',
			src:'../../static/images/module/function23@3x.png'
		},
		{
			value:'function24',
			src:'../../static/images/module/function24@3x.png'
		},
		{
			value:'function25',
			src:'../../static/images/module/function25@3x.png'
		},
		{
			value:'function26',
			src:'../../static/images/module/function26@3x.png'
		},
		{
			value:'function27',
			src:'../../static/images/module/function27@3x.png'
		},
		{
			value:'function28',
			src:'../../static/images/module/function28@3x.png'
		},
		{
			value:'function29',
			src:'../../static/images/module/function29@3x.png'
		},
		{
			value:'function30',
			src:'../../static/images/module/function30@3x.png'
		},
		{
			value:'function31',
			src:'../../static/images/module/function31@3x.png'
		},
		{
			value:'function32',
			src:'../../static/images/module/function32@3x.png'
		},
		{
			value:'function33',
			src:'../../static/images/module/function33@3x.png'
		},
		{
			value:'function34',
			src:'../../static/images/module/function34@3x.png'
		},
		{
			value:'function35',
			src:'../../static/images/module/function35@3x.png'
		},
		{
			value:'function36',
			src:'../../static/images/module/function36@3x.png'
		},
		{
			value:'function37',
			src:'../../static/images/module/function37@3x.png'
		},
		{
			value:'function38',
			src:'../../static/images/module/function38@3x.png'
		},
		{
			value:'function39',
			src:'../../static/images/module/function39@3x.png'
		},
		{
			value:'function40',
			src:'../../static/images/module/function40@3x.png'
		},
		{
			value:'function41',
			src:'../../static/images/module/function41@3x.png'
		},
		{
			value:'function42',
			src:'../../static/images/module/function42@3x.png'
		},
		{
			value:'function43',
			src:'../../static/images/module/function43@3x.png'
		},
		{
			value:'function44',
			src:'../../static/images/module/function44@3x.png'
		},
		{
			value:'function45',
			src:'../../static/images/module/function45@3x.png'
		},
		{
			value:'function46',
			src:'../../static/images/module/function46@3x.png'
		},
		{
			value:'function47',
			src:'../../static/images/module/function47@3x.png'
		},
	]
});

